$('.carousel').slick({
    dots:true,
    slidesPerRow:3,
    rows:2,
    responsive:[
        {
            breqkpoint:478,
            settings:{
                slidesPerRow:1,
                rows:1
            }
        }
    ]
});